import type { ParticipantStats } from "../../../types/participantStats";
import type { InputSection } from "./statsInputs";

type BuildInputsData = {
	p1: ParticipantStats;
	p2: ParticipantStats;
	p3?: ParticipantStats | null;
	p4?: ParticipantStats | null;
};

export function buildStatsInputsSections({
	p1,
	p2,
	p3,
	p4,
}: BuildInputsData): InputSection[] {
	return [
		{
			title: "Servicio",
			row: [
				{
					name: "Aces",
					property: "aces",
					p1Value: p1.aces,
					p2Value: p2.aces,
					p3Value: p3?.aces,
					p4Value: p4?.aces,
				},
				{
					name: "Doble faltas",
					property: "dobleFaults",
					p1Value: p1.dobleFaults,
					p2Value: p2.dobleFaults,
					p3Value: p3?.dobleFaults,
					p4Value: p4?.dobleFaults,
				},
				{
					name: "1er servicio in",
					property: "firstServIn",
					p1Value: p1.firstServIn,
					p2Value: p2.firstServIn,
					p3Value: p3?.firstServIn,
					p4Value: p4?.firstServIn,
				},
				{
					name: "1er saque ganador",
					property: "firstServWon",
					p1Value: p1.firstServWon,
					p2Value: p2.firstServWon,
					p3Value: p3?.firstServWon,
					p4Value: p4?.firstServWon,
				},
				{
					name: "Puntos ganados con el 1er servicio",
					property: "pointsWinnedFirstServ",
					p1Value: p1.pointsWinnedFirstServ,
					p2Value: p2.pointsWinnedFirstServ,
					p3Value: p3?.pointsWinnedFirstServ,
					p4Value: p4?.pointsWinnedFirstServ,
				},
				{
					name: "2do servicio in",
					property: "secondServIn",
					p1Value: p1.secondServIn,
					p2Value: p2.secondServIn,
					p3Value: p3?.secondServIn,
					p4Value: p4?.secondServIn,
				},
				{
					name: "2do saque ganador",
					property: "secondServWon",
					p1Value: p1.secondServWon,
					p2Value: p2.secondServWon,
					p3Value: p3?.secondServWon,
					p4Value: p4?.secondServWon,
				},
				{
					name: "Puntos ganados con el 2do servicio",
					property: "pointsWinnedSecondServ",
					p1Value: p1.pointsWinnedSecondServ,
					p2Value: p2.pointsWinnedSecondServ,
					p3Value: p3?.pointsWinnedSecondServ,
					p4Value: p4?.pointsWinnedSecondServ,
				},
				{
					name: "Break points salvados",
					property: "breakPtsSaved",
					p1Value: p1.breakPtsSaved,
					p2Value: p2.breakPtsSaved,
					p3Value: p3?.breakPtsSaved,
					p4Value: p4?.breakPtsSaved,
				},
				{
					name: "Chances de salvar break point",
					property: "saveBreakPtsChances",
					p1Value: p1.saveBreakPtsChances,
					p2Value: p2.saveBreakPtsChances,
					p3Value: p3?.saveBreakPtsChances,
					p4Value: p4?.saveBreakPtsChances,
				},
				{
					name: "Games ganados con el servicio",
					property: "gamesWonServing",
					p1Value: p1.gamesWonServing,
					p2Value: p2.gamesWonServing,
					p3Value: p3?.gamesWonServing,
					p4Value: p4?.gamesWonServing,
				},
				{
					name: "Games perdidos con el servicio",
					property: "gamesLostServing",
					p1Value: p1.gamesLostServing,
					p2Value: p2.gamesLostServing,
					p3Value: p3?.gamesLostServing,
					p4Value: p4?.gamesLostServing,
				},
			],
		},
		{
			title: "Devolución",
			row: [
				{
					name: "1era devolución in",
					property: "firstReturnIn",
					p1Value: p1.firstReturnIn,
					p2Value: p2.firstReturnIn,
					p3Value: p3?.firstReturnIn,
					p4Value: p4?.firstReturnIn,
				},
				{
					name: "1era devolución out",
					property: "firstReturnOut",
					p1Value: p1.firstReturnOut,
					p2Value: p2.firstReturnOut,
					p3Value: p3?.firstReturnOut,
					p4Value: p4?.firstReturnOut,
				},
				{
					name: "1era devolución ganadora",
					property: "firstReturnWon",
					p1Value: p1.firstReturnWon,
					p2Value: p2.firstReturnWon,
					p3Value: p3?.firstReturnWon,
					p4Value: p4?.firstReturnWon,
				},
				{
					name: "Winner con 1era devolución",
					property: "firstReturnWinner",
					p1Value: p1.firstReturnWinner,
					p2Value: p2.firstReturnWinner,
					p3Value: p3?.firstReturnWinner,
					p4Value: p4?.firstReturnWinner,
				},
				{
					name: "Puntos ganados con la 1era devolución",
					property: "pointsWinnedFirstReturn",
					p1Value: p1.pointsWinnedFirstReturn,
					p2Value: p2.pointsWinnedFirstReturn,
					p3Value: p3?.pointsWinnedFirstReturn,
					p4Value: p4?.pointsWinnedFirstReturn,
				},
				{
					name: "2da devolución in",
					property: "secondReturnIn",
					p1Value: p1.secondReturnIn,
					p2Value: p2.secondReturnIn,
					p3Value: p3?.secondReturnIn,
					p4Value: p4?.secondReturnIn,
				},
				{
					name: "2da devolución out",
					property: "secondReturnOut",
					p1Value: p1.secondReturnOut,
					p2Value: p2.secondReturnOut,
					p3Value: p3?.secondReturnOut,
					p4Value: p4?.secondReturnOut,
				},
				{
					name: "2da devolución ganadora",
					property: "secondReturnWon",
					p1Value: p1.secondReturnWon,
					p2Value: p2.secondReturnWon,
					p3Value: p3?.secondReturnWon,
					p4Value: p4?.secondReturnWon,
				},
				{
					name: "Winner con 2da devolución",
					property: "secondReturnWinner",
					p1Value: p1.secondReturnWinner,
					p2Value: p2.secondReturnWinner,
					p3Value: p3?.secondReturnWinner,
					p4Value: p4?.secondReturnWinner,
				},
				{
					name: "Puntos ganados con la 2da devolución",
					property: "pointsWinnedSecondReturn",
					p1Value: p1.pointsWinnedSecondReturn,
					p2Value: p2.pointsWinnedSecondReturn,
					p3Value: p3?.pointsWinnedSecondReturn,
					p4Value: p4?.pointsWinnedSecondReturn,
				},
				{
					name: "Break points",
					property: "breakPts",
					p1Value: p1.breakPts,
					p2Value: p2.breakPts,
					p3Value: p3?.breakPts,
					p4Value: p4?.breakPts,
				},
				{
					name: "Chanches de break point",
					property: "breakPtsChances",
					p1Value: p1.breakPtsChances,
					p2Value: p2.breakPtsChances,
					p3Value: p3?.breakPtsChances,
					p4Value: p4?.breakPtsChances,
				},
				{
					name: "Games ganados devolviendo",
					property: "gamesWonReturning",
					p1Value: p1.gamesWonReturning,
					p2Value: p2.gamesWonReturning,
					p3Value: p3?.gamesWonReturning,
					p4Value: p4?.gamesWonReturning,
				},
				{
					name: "Games perdidos devolviendo",
					property: "gamesLostReturning",
					p1Value: p1.gamesLostReturning,
					p2Value: p2.gamesLostReturning,
					p3Value: p3?.gamesLostReturning,
					p4Value: p4?.gamesLostReturning,
				},
			],
		},
		{
			title: "Pelota en Juego",
			row: [
				{
					name: "Puntos ganados en malla",
					property: "meshPointsWon",
					p1Value: p1.meshPointsWon,
					p2Value: p2.meshPointsWon,
					p3Value: p3?.meshPointsWon,
					p4Value: p4?.meshPointsWon,
				},
				{
					name: "Puntos perdidos en malla",
					property: "meshPointsLost",
					p1Value: p1.meshPointsLost,
					p2Value: p2.meshPointsLost,
					p3Value: p3?.meshPointsLost,
					p4Value: p4?.meshPointsLost,
				},
				{
					name: "Winners en malla",
					property: "meshWinner",
					p1Value: p1.meshWinner,
					p2Value: p2.meshWinner,
					p3Value: p3?.meshWinner,
					p4Value: p4?.meshWinner,
				},
				{
					name: "Errores en malla",
					property: "meshError",
					p1Value: p1.meshError,
					p2Value: p2.meshError,
					p3Value: p3?.meshError,
					p4Value: p4?.meshError,
				},
				{
					name: "Puntos ganados en fondo/approach",
					property: "bckgPointsWon",
					p1Value: p1.bckgPointsWon,
					p2Value: p2.bckgPointsWon,
					p3Value: p3?.bckgPointsWon,
					p4Value: p4?.bckgPointsWon,
				},
				{
					name: "Puntos perdidos en fondo/approach",
					property: "bckgPointsLost",
					p1Value: p1.bckgPointsLost,
					p2Value: p2.bckgPointsLost,
					p3Value: p3?.bckgPointsLost,
					p4Value: p4?.bckgPointsLost,
				},
				{
					name: "Winners en fondo/approach",
					property: "bckgWinner",
					p1Value: p1.bckgWinner,
					p2Value: p2.bckgWinner,
					p3Value: p3?.bckgWinner,
					p4Value: p4?.bckgWinner,
				},
				{
					name: "Errores en fondo/approach",
					property: "bckgError",
					p1Value: p1.bckgError,
					p2Value: p2.bckgError,
					p3Value: p3?.bckgError,
					p4Value: p4?.bckgError,
				},
			],
		},
		{
			title: "Puntos",
			row: [
				{
					name: "Puntos cortos ganados",
					property: "shortRallyWon",
					p1Value: p1.shortRallyWon,
					p2Value: p2.shortRallyWon,
					p3Value: p3?.shortRallyWon,
					p4Value: p4?.shortRallyWon,
				},
				{
					name: "Puntos cortos perdidos",
					property: "shortRallyLost",
					p1Value: p1.shortRallyLost,
					p2Value: p2.shortRallyLost,
					p3Value: p3?.shortRallyLost,
					p4Value: p4?.shortRallyLost,
				},
				{
					name: "Puntos medianos ganados",
					property: "mediumRallyWon",
					p1Value: p1.mediumRallyWon,
					p2Value: p2.mediumRallyWon,
					p3Value: p3?.mediumRallyWon,
					p4Value: p4?.mediumRallyWon,
				},
				{
					name: "Puntos medianos perdidos",
					property: "mediumRallyLost",
					p1Value: p1.mediumRallyLost,
					p2Value: p2.mediumRallyLost,
					p3Value: p3?.mediumRallyLost,
					p4Value: p4?.mediumRallyLost,
				},
				{
					name: "Puntos largos ganados",
					property: "longRallyWon",
					p1Value: p1.longRallyWon,
					p2Value: p2.longRallyWon,
					p3Value: p3?.longRallyWon,
					p4Value: p4?.longRallyWon,
				},
				{
					name: "Puntos largos perdidos",
					property: "longRallyLost",
					p1Value: p1.longRallyLost,
					p2Value: p2.longRallyLost,
					p3Value: p3?.longRallyLost,
					p4Value: p4?.longRallyLost,
				},
			],
		},
	];
}
